CREATE TRIGGER "ROLE_MAINTENANCE"."auth.auth::TR_FILL_PRTSCHEMA_INSERTTIME" AFTER INSERT ON "ROLE_MAINTENANCE"."auth.auth.tables::PROTECTED_SCHEMA_TABLES_IMPORT_LIST" REFERENCING NEW ROW MYNEWROW FOR EACH ROW 
BEGIN INSERT 
INTO "ROLE_MAINTENANCE"."auth.auth.tables::PROTECTED_SCHEMA_TABLES_IMPORT_LIST_TIMESTAMP" VALUES (:mynewrow.TABLE_NAME,
	 :mynewrow.CONTENT_PACKAGE,
	 :mynewrow.SCHEMA_NAME,
	 current_timestamp,
	 :mynewrow.TICKET_NUMBER) 
;							
 
END 
;